name: Unit Tests

on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'    

jobs:

  build:
    
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          # no libssl on windows
          # - windows-latest

        perl:
          - '5.22'
          - '5.26'
          - '5.30'
          - '5.32'
 
      fail-fast: false

    name: perl${{ matrix.perl }}/${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: CPAN Cache
      id: cpan-cache
      uses: actions/cache@v1
      with:
        path: thirdparty
        key: ${{ matrix.os }}-cpan-${{ matrix.perl }}-${{ hashFiles('**/Makefile.PL') }}-${{ hashFiles('**/cpanfile') }}

    - name: Prepare
      run: perl Makefile.PL

    - name: Make 3rd Party
      if: steps.cpan-cache.outputs.cache-hit != 'true'
      run: make thirdparty
      
    - name: Run tests
      run: |
        set -e
        make
        make test
        make dist
